// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: acme.proto

package acme

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ACME_Challenge_FullMethodName  = "/acme.ACME/Challenge"
	ACME_Cached_FullMethodName     = "/acme.ACME/Cached"
	ACME_Resolution_FullMethodName = "/acme.ACME/Resolution"
)

// ACMEClient is the client API for ACME service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ACME service is used by the internal RPC server to resolve acme challenges.
// it achieves this by using rendezvous hashing to have the servers agree on
// a proxy peer who is responsible for resolving challenges.
type ACMEClient interface {
	// initiates a certificate signing request.
	Challenge(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
	// return the cached certificate for the cluster.
	Cached(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
	// returns the resolution to a challenge.
	Resolution(ctx context.Context, in *ResolutionRequest, opts ...grpc.CallOption) (*ResolutionResponse, error)
}

type aCMEClient struct {
	cc grpc.ClientConnInterface
}

func NewACMEClient(cc grpc.ClientConnInterface) ACMEClient {
	return &aCMEClient{cc}
}

func (c *aCMEClient) Challenge(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, ACME_Challenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCMEClient) Cached(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, ACME_Cached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCMEClient) Resolution(ctx context.Context, in *ResolutionRequest, opts ...grpc.CallOption) (*ResolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolutionResponse)
	err := c.cc.Invoke(ctx, ACME_Resolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ACMEServer is the server API for ACME service.
// All implementations must embed UnimplementedACMEServer
// for forward compatibility.
//
// ACME service is used by the internal RPC server to resolve acme challenges.
// it achieves this by using rendezvous hashing to have the servers agree on
// a proxy peer who is responsible for resolving challenges.
type ACMEServer interface {
	// initiates a certificate signing request.
	Challenge(context.Context, *CertificateRequest) (*CertificateResponse, error)
	// return the cached certificate for the cluster.
	Cached(context.Context, *CertificateRequest) (*CertificateResponse, error)
	// returns the resolution to a challenge.
	Resolution(context.Context, *ResolutionRequest) (*ResolutionResponse, error)
	mustEmbedUnimplementedACMEServer()
}

// UnimplementedACMEServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedACMEServer struct{}

func (UnimplementedACMEServer) Challenge(context.Context, *CertificateRequest) (*CertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Challenge not implemented")
}
func (UnimplementedACMEServer) Cached(context.Context, *CertificateRequest) (*CertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cached not implemented")
}
func (UnimplementedACMEServer) Resolution(context.Context, *ResolutionRequest) (*ResolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolution not implemented")
}
func (UnimplementedACMEServer) mustEmbedUnimplementedACMEServer() {}
func (UnimplementedACMEServer) testEmbeddedByValue()              {}

// UnsafeACMEServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ACMEServer will
// result in compilation errors.
type UnsafeACMEServer interface {
	mustEmbedUnimplementedACMEServer()
}

func RegisterACMEServer(s grpc.ServiceRegistrar, srv ACMEServer) {
	// If the following call pancis, it indicates UnimplementedACMEServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ACME_ServiceDesc, srv)
}

func _ACME_Challenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACMEServer).Challenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACME_Challenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACMEServer).Challenge(ctx, req.(*CertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACME_Cached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACMEServer).Cached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACME_Cached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACMEServer).Cached(ctx, req.(*CertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACME_Resolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACMEServer).Resolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACME_Resolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACMEServer).Resolution(ctx, req.(*ResolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ACME_ServiceDesc is the grpc.ServiceDesc for ACME service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ACME_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acme.ACME",
	HandlerType: (*ACMEServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Challenge",
			Handler:    _ACME_Challenge_Handler,
		},
		{
			MethodName: "Cached",
			Handler:    _ACME_Cached_Handler,
		},
		{
			MethodName: "Resolution",
			Handler:    _ACME_Resolution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "acme.proto",
}
