// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

/*
Package cluster is a generated protocol buffer package.

It is generated from these files:
	cluster.proto

It has these top-level messages:
	Metadata
*/
package cluster

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Metadata struct {
	Capability []byte `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	RPCPort    uint32 `protobuf:"varint,2,opt,name=RPCPort" json:"RPCPort,omitempty"`
	RaftPort   uint32 `protobuf:"varint,3,opt,name=RaftPort" json:"RaftPort,omitempty"`
	SWIMPort   uint32 `protobuf:"varint,4,opt,name=SWIMPort" json:"SWIMPort,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Metadata) GetCapability() []byte {
	if m != nil {
		return m.Capability
	}
	return nil
}

func (m *Metadata) GetRPCPort() uint32 {
	if m != nil {
		return m.RPCPort
	}
	return 0
}

func (m *Metadata) GetRaftPort() uint32 {
	if m != nil {
		return m.RaftPort
	}
	return 0
}

func (m *Metadata) GetSWIMPort() uint32 {
	if m != nil {
		return m.SWIMPort
	}
	return 0
}

func init() {
	proto.RegisterType((*Metadata)(nil), "cluster.metadata")
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0x29, 0x2d,
	0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x6a, 0xb8,
	0x38, 0x72, 0x53, 0x4b, 0x12, 0x53, 0x12, 0x4b, 0x12, 0x85, 0xe4, 0xb8, 0xb8, 0x92, 0x13, 0x0b,
	0x12, 0x93, 0x32, 0x73, 0x32, 0x4b, 0x2a, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x90, 0x44,
	0x84, 0x24, 0xb8, 0xd8, 0x83, 0x02, 0x9c, 0x03, 0xf2, 0x8b, 0x4a, 0x24, 0x98, 0x14, 0x18, 0x35,
	0x78, 0x83, 0x60, 0x5c, 0x21, 0x29, 0x2e, 0x8e, 0xa0, 0xc4, 0xb4, 0x12, 0xb0, 0x14, 0x33, 0x58,
	0x0a, 0xce, 0x07, 0xc9, 0x05, 0x87, 0x7b, 0xfa, 0x82, 0xe5, 0x58, 0x20, 0x72, 0x30, 0x7e, 0x12,
	0x1b, 0xd8, 0x35, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xbf, 0x01, 0x3a, 0x9e, 0x00,
	0x00, 0x00,
}
