// Code generated by "stringer -type=ErrorEnum -type=InfoEnum -type=ExitEnum"; DO NOT EDIT.

package packagekit

import "fmt"

const _ExitEnum_name = "ExitUnknownExitSuccessExitFailedExitCancelledExitKeyRequiredExitEULARequiredExitKilledExitMediaChangeRequiredExitNeedUntrustedExitCancelledPriorityExitSkipTransactionExitRepairRequired"

var _ExitEnum_index = [...]uint8{0, 11, 22, 32, 45, 60, 76, 86, 109, 126, 147, 166, 184}

func (i ExitEnum) String() string {
	if i >= ExitEnum(len(_ExitEnum_index)-1) {
		return fmt.Sprintf("ExitEnum(%d)", i)
	}
	return _ExitEnum_name[_ExitEnum_index[i]:_ExitEnum_index[i+1]]
}
