// Code generated by "stringer -type=ErrorEnum -type=InfoEnum -type=ExitEnum"; DO NOT EDIT.

package packagekit

import "strconv"

const _ExitEnum_name = "ExitUnknownExitSuccessExitFailedExitCancelledExitKeyRequiredExitEULARequiredExitKilledExitMediaChangeRequiredExitNeedUntrustedExitCancelledPriorityExitSkipTransactionExitRepairRequired"

var _ExitEnum_index = [...]uint8{0, 11, 22, 32, 45, 60, 76, 86, 109, 126, 147, 166, 184}

func (i ExitEnum) String() string {
	if i >= ExitEnum(len(_ExitEnum_index)-1) {
		return "ExitEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitEnum_name[_ExitEnum_index[i]:_ExitEnum_index[i+1]]
}
